apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextgenz-deploy
  name: nextgenz-deploy
  namespace: nextgenz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextgenz-deploy
  template:
    metadata:
      labels:
        app: nextgenz-deploy
    spec:
      containers:
      - name: nextgenz-deploy
        image: 475698774125.dkr.ecr.us-east-1.amazonaws.com/nextgenz:latest
        ports:
        - containerPort: 5000
        envFrom:
          - secretRef:
              name: nextgenz-secret
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"

