apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-cpu-scaledobject
  namespace: nextgenz
spec:
  minReplicaCount: 3
  maxReplicaCount: 6
  scaleTargetRef:
    name: nginx-deploy
    kind: Deployment
    apiVersion: apps/v1
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "50"
