apiVersion: v1
kind: Secret
metadata:
  name: nextgenz-secret
  namespace: nextgenz
type: Opaque
stringData:
  DB_HOST: nextgenz-prod-db-instance.csjqigg6kv59.us-east-1.rds.amazonaws.com
  DB_USER: admin
  DB_PASSWORD: S3nai!S3cret134
  DB_NAME: nextgenzdb

