apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextgenz-svc
  name: nextgenz-svc
  namespace: nextgenz
spec:
  ports:
  - name: ports
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: nextgenz-deploy
  type: ClusterIP
status:
  loadBalancer: {}
